version: '3'
services:
  app:
    image: kitanoyoru/lead-hist-python-task:latest
    ports:
      - ${APP_PORT}:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ../data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_REPLICA_HOST=host.docker.internal
      - MONGO_REPLICA_PORT=27018

